Repository thoth-station/s2i-minimal-notebook, pull requests merged in 2020-08, with the labels that each got.

#7 Update jupyterlab/hub
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#6 include only necessary oc binaries
  .s2i/bin/assemble
  oc-wrapper.sh
Labels: approved, size/M

#11 Release of version 0.0.6
  CHANGELOG.md
  thoth/s2i-minimal-notebook/__init__.py
Labels: approved, bot, size/M
