Repository thoth-station/s2i-minimal-notebook, pull requests merged in 2021-11, with the labels that each got.

#191 Images optimization
  .s2i/bin/assemble
  .thoth.yaml
  overlays/f34-python39/Dockerfile
  overlays/python36/Dockerfile
  overlays/python38/Dockerfile
Labels: approved, size/M, ok-to-test

#192 Add spellchecker and update jupyterlab-requirements extensions
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.in
  overlays/python38/requirements.txt
Labels: approved, size/XL

#224 Updated the dependencies for the overlays
  overlays/f34-python39/Pipfile
  overlays/f34-python39/Pipfile.lock
  overlays/f34-python39/requirements.in
  overlays/f34-python39/requirements.txt
  overlays/python36/Pipfile
  overlays/python36/Pipfile.lock
  overlays/python36/requirements.in
  overlays/python36/requirements.txt
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.in
  overlays/python38/requirements.txt
Labels: approved, size/XXL

#489 Bump jupyterlab-requirements to v0.13.0
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.in
  overlays/python38/requirements.txt
Labels: approved, size/XXL
