Repository thoth-station/s2i-minimal-notebook, pull requests merged in 2022-09, with the labels that each got.

#577 :pray: Correct the release version to v0.4.1 from v1.0.0
  CHANGELOG.md
  thoth/s2i-minimal-notebook/__init__.py
Labels: approved, size/XS

#578 Automatic update of base-image in CI
  .thoth.yaml
Labels: approved, size/XS, ok-to-test

#587 Introduce ubi8-py39 and ubi9-py39 based minimal notebook
  .aicoe-ci.yaml
  .thoth.yaml
  README.md
  overlays/ubi8-py39/Dockerfile
  overlays/ubi8-py39/Pipfile
  overlays/ubi8-py39/Pipfile.lock
  overlays/ubi8-py39/requirements.in
  overlays/ubi8-py39/requirements.txt
  overlays/ubi9-py39/Dockerfile
  overlays/ubi9-py39/Pipfile
  overlays/ubi9-py39/Pipfile.lock
  overlays/ubi9-py39/requirements.in
  overlays/ubi9-py39/requirements.txt
Labels: approved, size/XXL

#588 Update the python dependencies for all overlays
  overlays/f34-python39/Pipfile.lock
  overlays/f34-python39/requirements.txt
  overlays/f35-python310/Pipfile.lock
  overlays/f35-python310/requirements.txt
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.txt
Labels: approved, size/XXL
