Repository thoth-station/s2i-minimal-notebook, pull requests merged in 2022-11, with the labels that each got.

#603 :sparkles: update the base image to v0.35.1
  overlays/f34-python39/Dockerfile
  overlays/f35-python310/Dockerfile
  overlays/python36/Dockerfile
  overlays/python38/Dockerfile
  overlays/ubi8-py39/Dockerfile
  overlays/ubi9-py39/Dockerfile
Labels: approved, size/S, lgtm

#604 Automatic update of base-image in CI
  .thoth.yaml
Labels: approved, size/S, lgtm, ok-to-test

#547 Include nbgitpuller in the notebook images
  overlays/f34-python39/Pipfile
  overlays/f34-python39/Pipfile.lock
  overlays/f34-python39/requirements.in
  overlays/f34-python39/requirements.txt
  overlays/f35-python310/Pipfile
  overlays/f35-python310/Pipfile.lock
  overlays/f35-python310/requirements.in
  overlays/f35-python310/requirements.txt
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.in
  overlays/python38/requirements.txt
  overlays/ubi8-py39/Pipfile
  overlays/ubi8-py39/Pipfile.lock
  overlays/ubi8-py39/requirements.in
  overlays/ubi8-py39/requirements.txt
  overlays/ubi9-py39/Pipfile
  overlays/ubi9-py39/Pipfile.lock
  overlays/ubi9-py39/requirements.in
  overlays/ubi9-py39/requirements.txt
Labels: size/XXL

#605 :recycle: HouseKeeping: Updated pre-commit and OWNERS
  .pre-commit-config.yaml
  .thoth.yaml
  OWNERS
Labels: size/S

#607 :clipboard: Include list of images in table format
  README.md
Labels: size/S

#609 :ship: Release of version 0.5.1
  CHANGELOG.md
  thoth/s2i-minimal-notebook/__init__.py
Labels: size/S
