Repository thoth-station/s2i-minimal-notebook, pull requests merged in 2022-07, with the labels that each got.

#546 Set the env vars and labels for the s2i-minimal images
  overlays/f34-python39/Dockerfile
  overlays/f35-python310/Dockerfile
  overlays/python36/Dockerfile
  overlays/python38/Dockerfile
Labels: approved, size/L

#555 Readme fix and mod_wsgi update
  .s2i/bin/assemble
  README.md
Labels: approved, size/XS, lgtm, ok-to-test

#560 :whale: Include jupyter server proxy in minimal
  overlays/f34-python39/Pipfile
  overlays/f34-python39/Pipfile.lock
  overlays/f35-python310/Pipfile
  overlays/f35-python310/Pipfile.lock
  overlays/python36/Pipfile
  overlays/python36/Pipfile.lock
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
Labels: size/XXL

#562 :arrow_up: Updated the base image for the all overlays
  .thoth.yaml
  overlays/f34-python39/Dockerfile
  overlays/f35-python310/Dockerfile
  overlays/python36/Dockerfile
  overlays/python38/Dockerfile
Labels: size/S
