Repository thoth-station/s2i-minimal-notebook, pull requests merged in 2022-03, with the labels that each got.

#519 Automatic update of base-image in CI
  .thoth.yaml
Labels: approved, size/XS, ok-to-test

#526 setup minimal image for f35 with py 3.10
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .thoth.yaml
  OWNERS
  README.md
  overlays/f35-python310/Dockerfile
  overlays/f35-python310/Pipfile
  overlays/f35-python310/Pipfile.lock
  overlays/f35-python310/requirements.in
  overlays/f35-python310/requirements.txt
Labels: approved, size/XXL

#527 set the latest build to be tagged release
  .aicoe-ci.yaml
Labels: approved, size/XS

#531 Include jupyterlab tabnine support in minimal
  overlays/f34-python39/Pipfile
  overlays/f34-python39/Pipfile.lock
  overlays/f34-python39/requirements.in
  overlays/f34-python39/requirements.txt
  overlays/f35-python310/Pipfile
  overlays/f35-python310/Pipfile.lock
  overlays/f35-python310/requirements.in
  overlays/f35-python310/requirements.txt
  overlays/python36/Pipfile
  overlays/python36/Pipfile.lock
  overlays/python36/requirements.in
  overlays/python36/requirements.txt
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.in
  overlays/python38/requirements.txt
Labels: approved, size/XXL

#532 Update the jupyterhub version for secruity
  overlays/f34-python39/Pipfile
  overlays/f34-python39/Pipfile.lock
  overlays/f34-python39/requirements.in
  overlays/f34-python39/requirements.txt
  overlays/f35-python310/Pipfile
  overlays/f35-python310/Pipfile.lock
  overlays/f35-python310/requirements.in
  overlays/f35-python310/requirements.txt
  overlays/python36/Pipfile
  overlays/python36/Pipfile.lock
  overlays/python36/requirements.in
  overlays/python36/requirements.txt
  overlays/python38/Pipfile
  overlays/python38/Pipfile.lock
  overlays/python38/requirements.in
  overlays/python38/requirements.txt
Labels: approved, size/L
